### ISSUE TITLE
[Suggestion] Block map creation if you don't have permission.

### ISSUE THREAD

**Issue by SrBedrock** [GPAddons/GPExtraProtections#2]
A system would be very useful where the player without permission to access cannot create maps of the location.
This would help players who make mapart protect their canvas

**Comment by Jikoo** [comment]
Had a bit of a look at this, it's not possible to futureproof due to limitations of the map API. I'll have a stab at it, but it'll likely break if Mojang changes how maps work.

**Comment by Jikoo** [comment]
Actually, on further inspection I'm going to decline this. See https://minecraft.gamepedia.com/Map#Locking
